const EmptyChatSvg = () => {
  return (
    <svg
      className=""
      xmlns="http://www.w3.org/2000/svg"
      width="190px"
      height="190px"
      viewBox="0 0 426 349"
      fill="none"
    >
      <rect
        x="70"
        y="49"
        width="325"
        height="173"
        rx="17"
        fill="var(--background)"
      />
      <rect
        x="70"
        y="49"
        width="325"
        height="173"
        rx="17"
        stroke="var(--border)"
      />
      <rect
        x="100"
        y="86"
        width="208"
        height="12"
        rx="4"
        fill="var(--border)"
      />
      <rect
        x="100"
        y="124"
        width="265"
        height="12"
        rx="4"
        fill="var(--border)"
      />
      <rect
        x="1"
        y="135"
        width="325"
        height="173"
        rx="17"
        fill="var(--background)"
      />
      <rect
        x="1"
        y="135"
        width="325"
        height="173"
        rx="17"
        stroke="var(--border)"
      />
      <rect
        x="31"
        y="172"
        width="208"
        height="12"
        rx="4"
        fill="var(--border)"
      />
      <rect
        x="31"
        y="210"
        width="265"
        height="12"
        rx="4"
        fill="var(--border)"
      />
      <circle
        cx="271.5"
        cy="29.5"
        r="11.5"
        fill="var(--background)"
        stroke="var(--border)"
      />
      <circle
        cx="348.5"
        cy="260.5"
        r="11.5"
        fill="var(--background)"
        stroke="var(--border)"
      />
      <circle
        cx="126.5"
        cy="336.5"
        r="11.5"
        fill="var(--background)"
        stroke="var(--border)"
      />
      <circle
        cx="30.5"
        cy="86.5"
        r="11.5"
        fill="var(--background)"
        stroke="var(--border)"
      />
      <line
        x1="149.5"
        y1="1.5"
        x2="149.5"
        y2="16.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="157.5"
        y1="8.5"
        x2="142.5"
        y2="8.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="50.5"
        y1="99.5"
        x2="50.5"
        y2="114.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="58.5"
        y1="106.5"
        x2="43.5"
        y2="106.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="282.5"
        y1="317.5"
        x2="282.5"
        y2="332.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="290.5"
        y1="324.5"
        x2="275.5"
        y2="324.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="416.5"
        y1="119.5"
        x2="416.5"
        y2="134.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="424.5"
        y1="126.5"
        x2="409.5"
        y2="126.5"
        stroke="var(--background)"
        strokeWidth="3"
        strokeLinecap="round"
      />
    </svg>
  );
};

export default EmptyChatSvg;
