import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import { CounterStoreProvider } from "./providers/counter-store-provider";
import { Toaster } from "sonner";
const neueMontreal = LocalFont({
  src: [
    {
      path: "../../public/font/NeueMontreal-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/font/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/NeueMontreal-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/font/NeueMontreal-Bold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-neue",
  style: "normal",
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neueMontreal.variable} ${neueMontreal.variable} antialiased`}
      >
        <Toaster />
        <HomeLayout>{children}</HomeLayout>
      </body>
    </html>
  );
}

const HomeLayout = ({ children }: { children: React.ReactNode }) => {
  "use client";
  return <CounterStoreProvider>{children}</CounterStoreProvider>;
};
